version = 0.1

[default.deploy.parameters]
stack_name = "SchedulEase-Backendd"
resolve_s3 = true
s3_prefix = "SchedulEase-Backendd"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
